services:
  db:
    image: postgres:latest # Usa a imagem oficial mais recente do PostgreSQL
    container_name: assistencia-tecnica-db
    restart: always # Reinicia o contêiner se ele falhar
    environment:
      POSTGRES_USER: assistenciatecnica # Define o nome do usuário do banco
      POSTGRES_PASSWORD: assistencia@tecnica2025 # Define a senha do banco
      POSTGRES_DB: assistencia_tecnica_db # Define o nome do banco de dados
    ports:
      - "5432:5432" # Mapeia a porta 5432 do host para a 5432 do contêiner
    volumes:
      - pgdata:/var/lib/postgresql/data # Persiste os dados em um volume nomeado

volumes:
  pgdata: # Define o volume chamado pgdata para armazenar os dados

